### PR TITLE
First take for an easy way to implement "inherited attributes"

### PR DESCRIPTION
**Pull request by imliam**
A start on something that I'd like to see as raised in #109 

This PR in no way makes attributes actually inherited onto the root element, but instead introduces a new `@attributes` directive that will output the HTML for the attributes where the developer using BladeX requests. That helps if they don't necessarily want it on the root element, but a sub-element.

For example, let's say we have a component `x-button` that implements this directive:

```html
<button @attributes>{{ $slot }}</button>
```

When we use the component, on top of the regular BladeX behaviour of passing properties and binding values into the container, we can pass through attributes prefixed with a hyphen (`-`).

```html
<x-button -type="reset" -class="btn">Reset</x-button>
```

Any attributes prefixed with a hyphen will be output by the `@attributes` directive within that component. Our final output HTML will be:

```html
<button type="reset" class="btn">Reset</button>
```

This is an extremely naive approach but, to me, feels like it could work:
* It doesn't break backwards compatibility
* It still "feels" natural when writing HTML and using the Blade component
* The user of BladeX doesn't need to manually define every possible HTML attribute they might want to pass in when using the component
* The directive means it's not _limited_ to applying these attributes to the root element. This will be useful for more complex form elements than this example, such as an input wrapped in a div, and wanting to be able to automatically apply the attributes to an inner-element instead (such as `<x-input :value="$value" -required -inputmode="numeric" -pattern="0-9+" />`)

On the spot, I can see 2 areas that could be improved from here:
* Automatically apply these attributes to the root element of the component if usage `@attributes` is not found within the component
* Some way to handle potential duplicate attributes (such as if the developer sets the same attribute in the component and passed into the component)

Thoughts?

### CODE REVIEW

**Comment by freekmurze** [comment]
We will not be investing any more time in this package, as Laravel 7 will have native blade components.

**Comment by akiyamaSM** [comment]
@freekmurze They will not be using the BladeX package?

**Comment by imliam** [comment]
@akiyamaSM no, it'll be part of core (with some minor improvements ontop of BladeX's implementation too, from what I've seen)

**Comment by akiyamaSM** [comment]
@imliam I mean it will still load from that package? or it will be rewriting in the core?

**Comment by imliam** [comment]
@akiyamaSM the code is in the core framework now.

**Comment by akiyamaSM** [comment]
I seee thaaanks @imliam

**Pull request closed without merging**
