### PR TITLE
Extended BladeX::components() to take an array of directories.

### PR DESCRIPTION
**Pull request by telkins**
Pretty quick/easy, but it's certainly possible I've missed something.

I added a couple of tests that seem to cover the basics...all passing locally.

Not sure how I should have handled the invalid argument exception.  Wanted to piggy-back onto the `CouldNotRegisterComponent` exception class, but `InvalidArgumentException` seemed more appropriate.  No test for that, btw....but can add some if necessary.

### CODE REVIEW

**Comment by telkins** [comment]
Not sure I trust/understand the travis-ci failures.  For example, `ReflectionException: Class Spatie\BladeX\Tests\CouldNotRegisterComponent does not exist` in one test, but not the others that do the same.

Any insight/suggestions...?

**Comment by AlexVanderbist** [comment]
Looks like tests were already failing on irrelevant tests. You might want to rebase your commits onto origin/master to pull in the fixes (`git rebase origin/master`).

Also, can you add a new directory with 1 or 2 components to test with. Otherwise your tests will fail every time we add a new component to the test components directory :)

Apart from those tiny issues this looks good to me 👍 thanks!

**Comment by telkins** [comment]
@AlexVanderbist Thx for the feedback/advice.  I didn't consider what would happen to the tests when new components are added.  :-/

Anyway, I should be able to get to it shortly....I hope.  ;-)

**Comment by telkins** [comment]
OK.  All's done now.  I added two new component directories: `multi1` and `multi2`.  I'm not terribly creative with names, so if these are too boring, please come with some suggestions.  ;-)

Anyway, the tests are updated to use the new directories and the PR contains the latest from the `master` branch.

As usual, let me know if there are any issues/concerns.  Thx again.  :-)

**Comment by freekmurze** [comment]
Thanks!

**Comment by telkins** [comment]
@AlexVanderbist @freekmurze I just realized I forgot to update the docs....which is quite embarrassing since no developer has ever forgotten to update the docs before...!  ;-)

Anyway, I'll get that taken care of tomorrow.

**Pull request merged**
